name: email_otp
description: A fast & simple email authentication OTP sender and verification flutter package.
version: 3.0.2

environment:
  sdk: ">=2.17.0 <4.0.0" 
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - email
  - otp
  - smtp
  - authentication
